
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://tapanbk.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /blog

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Tapan B.K."
title: "Tapan BK"
description: "Blog and website of Tapan B.K., blogging mainly for tech. Opinions expressed are mine."
keywords: "Tapan B.K., tapan, full stack software engineer, python, Angular, JS"
favicon: "/img/favicon.ico"

################
# Header layout #
################

# page top right logo glass one
black-favicon: False

# page top right side logo bigger one github one
logo: "img/tapanbk_small_2.jpg" # leave blank if you don't want a logo

# Blur background one
background-img: "../img/tapanbk3.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"
  - text: "Be Awesome"
  - text: "Don’t worry if it doesn’t work right. If everything did, you’d be out of a job."
  - text: "In order to understand recursion, one must first understand recursion"
  - text: "Things are not always #000000 and #FFFFFF"
  - text: "If at first you don’t succeed; call it version 1.0"
  - text: "Code is like humor. When you have to explain it, it’s bad."
  - text: "Without requirements or design, programming is the art of adding bugs to an empty text file."
  - text: "One: Demonstrations always crash. And two: The probability of them crashing goes up exponentially with the number of people watching."
  - text: "How many programmers does it take to change a light bulb? None, that’s a hardware problem."

me-img: "/img/tapanbk_small.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#132a3e"
apple-status-bar-style: "red"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############

events:
  - company: "Outcode LLC"
    location: "Naxal Kathmandu Nepal"
    title: "Full Stack Software Engineer"
    image: "/img/timeline/gangnamtocat.png"
    date: "November 2020 - Today"

  - company: "Insight Workshop"
    location: "Naxal Kathmandu Nepal"
    title: "Software Engineer"
    image: "/img/timeline/privateinvestocat.jpg"
    date: "June 2018 - November 2020"

  - company: "Slash Plus"
    location: "Kumaripati Lalitpur Nepal"
    title: "Web Developer"
    image: "/img/timeline/labtocat.png"
    date: "March 2016 - June 2018"



# First image of the Timeline

timeline-img: "/img/timeline/spidertocat.png"

###########
# Contact #
###########

email: "bktapan16@gmail.com"
phone: "+977-9849716660"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Tapan B.K. is an awesome person. He lives in Kathmandu Nepal, where he works on awesome projects. In his spare time, John likes to watch movies, visit new places."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/tapanbk"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/tapanbk/"
  - title: "facebook"
    url: "https://facebook.com/tapan.bk"
  - title: "twitter"
    url: "https://twitter.com/tapanbk"

############
# 404 page #
############

err-404-img: "/img/gangnamtocat.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
